meta_product_name: "Tch誰n Raid Scheduler"
meta_title: "Tch誰n Raid Scheduler - Get on the best FR viewer raids !"
meta_description: "Tch誰n Raid Scheduler lets you apply for Tch誰n's viewer raids."
meta_image: "cover.png"                       # should exist in `app/assets/images/`
twitter_account: "@tchinq"
