# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8b9ea0fd58aab38d3a9a8e3021317dd8b60689752ad91ba652046f022d8940521bbbb9ba330c11ec5e3a892a9d3c1967ee172d1e7b24f9327c39421c291a8bd

test:
  secret_key_base: 7f4f9dfd0684bac416f55d78be83b0ae04a779fb5180b3893d743640cb39f3b642b47327a13ac29ddd546f0998e60da7497af1627c47cf848e2a3632801b21c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
